### ISSUE TITLE
VirtualBox download broken (again)

### ISSUE THREAD

**Issue by jessepeterson** [autopkg/jessepeterson-recipes#11]
See #3 for previous issue. Getting an odd reply to the update query:

```bash
curl 'https://update.virtualbox.org/query.php?platform=DARWIN_64BITS_GENERIC&version=4.3.16_95972&count=97&branch=stable'
```

Returns:

```
5.0.0_BETA4 http://download.virtualbox.org/virtualbox/4.3.28/VirtualBox-4.3.28-100309-OSX.dmg
```

I think usually the update string (first spare-separated result from the query) should match the DMG. But in this case it clearly doesn't. Not sure what to do about this. Waiting it out for now. Perhaps need to (finally) implement supplying a user agent to the query.

**Comment by RicknTx** [comment]
Thanks for looking into this.  I accidentally logged the issue in your old repo... didn't see it moved here.

**Comment by jessepeterson** [comment]
In the normal VirtualBox menu -> Check for Updates items what is the version presented to you? I seem to be getting presented with 4.3.28 for a VirtualBox 4.3.26 installation. Another 4.3.28 installation wants me to have this 5.0.0_BETA4 version. Could they be seeding the beta somehow to some users via the update feed to get testing and feedback?

**Comment by RicknTx** [comment]
Hi, 
I have 4.3.28 installed.  I run the autopkg inquiry via scheduled Jenkins jobs...  I don't know if this helps or not...  but when I run it there, this is what I get:

Building in workspace /Users/Shared/Jenkins/Home/workspace/VirtualBox
[VirtualBox] $ /bin/sh -xe /Users/Shared/Jenkins/tmp/hudson1195142385279919112.sh
+ /usr/local/bin/autopkg run VirtualBox.munki.recipe
No matching VirtualBox software
Failed.
Processing VirtualBox.munki.recipe...

The following recipes failed:
    VirtualBox.munki.recipe
        Error in com.github.jessepeterson.munki.VirtualBox: Processor: VirtualBoxURLProvider: Error: No matching VirtualBox software

Nothing downloaded, packaged or imported.
Build step 'Execute shell' marked build as failure

**Comment by jessepeterson** [comment]
Sure, yeah. But I'm trying to debug the update check mechanism. When you open the VirtualBox.app (in your Applications folder — that is *not* running autopkg) and then go to VirtualBox menu -> Check for Updates: what do you get as a reply?

I asked on IRC (#vbox on FreeNode) a few hours ago and they said to ask again on Monday (when the devs hang around) or submit a support ticket. Not sure if I'll get the time to do that but that's probably a next step.

**Comment by RicknTx** [comment]
Oh sorry about that...  When I run check for updates inside...  It says you have the most recent version.

Let me know if I can help further :)

**Comment by jessepeterson** [comment]
Interesting: 5 weeks ago VirtualBox changed their version checking code (in [this source file](https://www.virtualbox.org/browser/vbox/trunk/src/VBox/Frontends/VirtualBox/src/net/UIUpdateManager.cpp) in this [changeset](https://www.virtualbox.org/changeset/55739/vbox/trunk/src/VBox/Frontends/VirtualBox/src/net/UIUpdateManager.cpp)). It's just a small regular expression change but to me that hints that they changed things on the update server side.

I also note that if I change the above `curl` call to have the "current" version in the URL parameters (4.3.28), then I get a body reply of

    UPTODATE

Still to reach out to them to figure out what's up.

**Comment by jessepeterson** [comment]
So I never reached out to VirtualBox, instead just opting to work around the issue by parsing the version number out of the update server URL reply. If you want you could further find out what's going on by reaching out on the [VirtualBox Bugtracker](https://www.virtualbox.org/wiki/Bugtracker). Give it a go and let me know.

**Comment by jessepeterson** [comment]
I'm re-opening the issue. I submitted an issue to the VirtualBox folks [here](https://www.virtualbox.org/ticket/14730). Hopefully they'll reply on what's up.

**Comment by jessepeterson** [comment]
Oops, closing issue, meant to re-open other one.
