### ISSUE TITLE
Undefined key in variable substitution in Cisco AnyConnect.munki

### ISSUE THREAD

**Issue by grahamgilbert** [autopkg/jessepeterson-recipes#13]
I'm afraid I've not had time to do any debugging on this, but the error is below:

``` 
Processing AnyConnect.munki...
Use of undefined key in variable substitution: u'PKG'
Error processing path '%PKG%' with glob.
Failed.
```

**Comment by erikng** [comment]
Graham are you using the pkg from Cisco, or the pkg inside of the dmg (from Cisco)?

The pkg isn't really a package.

```Processing AnyConnect.munki...

The following new items were imported:
    Name                     Version          Catalogs                         Pkginfo Path
    ----                     -------          --------                         ------------
    AnyConnect               3.1.09013        testing                          apps/cisco/anyconnect/AnyConnect-3.1.09013.plist```

**Comment by grahamgilbert** [comment]
I've probably been guilty of not rtfm here - are we supposed to provide our own package? I just blindly made an override.

**Comment by erikng** [comment]
In this case yes, as there isn't a download processor (Cisco hides the package behind a login).

Perhaps someone could create a download processor with an override containing username/password, but that sounds dangerous.

**Comment by erikng** [comment]
FWIW, we are working on the same thing.

The current recipe needs some work. Since there is a XMLCC, perhaps an Installs array should be used rather than relying on receipts. Out of box, AnyConnect will loop.

**Comment by grahamgilbert** [comment]
Not so much trouble as the app updates when the vpn appliance tells it to. I'll get back in my box and won't just blindly ``autopkg search`` in future.

**Comment by jessepeterson** [comment]
@erikng Does this package loop out of the box? I do recall having to add the optional key to the receipts array, not sure if it that made it into the package or not. Perhaps I need to add in a processor step to change that automatically.

**Comment by erikng** [comment]
Yes it does. I opted for an installs array.

**Comment by jessepeterson** [comment]
Looks like @keeleysam has already solved this problem [here](https://github.com/autopkg/keeleysam-recipes/blob/master/GoogleTalkPlugin/MunkiPkginfoReceiptsEditor.py). I'll try to integrate his Processor using [shared processors](https://github.com/autopkg/autopkg/wiki/Processor-Locations#shared-recipe-processors).

**Comment by jessepeterson** [comment]
Should be fixed now with bc7a5ed610c83b844a70134478fbf53a7ad29fae.

**Comment by jessepeterson** [comment]
I added a new processor [here](6c0a210c47795249080b91fadd8eade34303b043) to give a more helpful error:

```bash
Mac:autopkg jesse$ Code/autopkg run AnyConnect.munki
Processing AnyConnect.munki...
This recipe requires a package or disk image to be pre-downloaded and supplied to autopkg ("-p" option). This is likely due to a login being required to download the software.
Failed.

The following recipes failed:
    AnyConnect.munki
        Error in local.munki.AnyConnect: Processor: PackageRequired: Error: This recipe requires a package or disk image to be pre-downloaded and supplied to autopkg ("-p" option). This is likely due to a login being required to download the software.

Nothing downloaded, packaged or imported.
```

Hopefully that's a bit more clear for folks attempting to run the recipe.

**Comment by erikng** [comment]
Nice!
