### ISSUE TITLE
Copier Error

### ISSUE THREAD

**Issue by wildeep** [autopkg/jessepeterson-recipes#14]
When running this recipe in AutoPKGr, I get this error:

Error in com.github.jessepeterson.munki.AnyConnect: Processor: Copier: Error: Error processing path '%PKG%' with glob.

**Comment by jessepeterson** [comment]
Cisco requires a login to download AnyConnect so you need to supply your own downloaded AnyConnect DMG. Run autopkg with the `-p` switch to provide a path to your downloaded package. Cheers.

**Comment by wildeep** [comment]
Thanks for your quick response, Jesse! Was there documentation that I should have read?

**Comment by jessepeterson** [comment]
Not particularly. :) The autopkg error isn't very clear about what's going on, though. I wonder if there's some way that could be improved.

**Comment by jessepeterson** [comment]
I added a new processor [here](6c0a210c47795249080b91fadd8eade34303b043) to give a more helpful error:

```bash
Mac:autopkg jesse$ Code/autopkg run AnyConnect.munki
Processing AnyConnect.munki...
This recipe requires a package or disk image to be pre-downloaded and supplied to autopkg ("-p" option). This is likely due to a login being required to download the software.
Failed.

The following recipes failed:
    AnyConnect.munki
        Error in local.munki.AnyConnect: Processor: PackageRequired: Error: This recipe requires a package or disk image to be pre-downloaded and supplied to autopkg ("-p" option). This is likely due to a login being required to download the software.

Nothing downloaded, packaged or imported.
```

Hopefully that's a bit more clear for folks attempting to run the recipe.
