### ISSUE TITLE
Missing processor in AnyConnect recipe

### ISSUE THREAD

**Issue by grahamgilbert** [autopkg/jessepeterson-recipes#15]
You took out the PackageRequired processor, but the recipe still uses it (https://github.com/autopkg/jessepeterson-recipes/blob/master/Cisco/AnyConnect.munki.recipe#L75-L76)

```
autopkg run AnyConnect.munki.recipe -k PKG=/Users/grahamgilbert/Downloads/anyconnect-macosx-4.1.04011-web-deploy-k9.dmg -k MUNKI_REPO_SUBDIR=apps/Cisco/AnyConnect
Processing AnyConnect.munki.recipe...
Failed.

The following recipes failed:
    AnyConnect.munki.recipe
        Unknown processor 'PackageRequired'.

Nothing downloaded, packaged or imported.
```

**Comment by gregneagle** [comment]
The PackageRequired processor is now part of the "included" processors in autopkg, though there has not yet been an official release that includes this,  Jesse should probably continue to include the processor with his recipe for now. Hopefully no-one else will use it from this location.

**Comment by jessepeterson** [comment]
Oops. I'll put it back in. :)

**Comment by jessepeterson** [comment]
Re-opening as a reminder to me to remove processor when autopkg is next released.
