### ISSUE TITLE
ImageJ64.app error in ImageJ.munki

### ISSUE THREAD

**Issue by andrewvalentine** [autopkg/jessepeterson-recipes#16]
Running the ImageJ.munki recipe is producing the following error:

`Error in com.github.jessepeterson.munki.ImageJ: Processor: Copier: Error: Can't copy /Users/*username*/Library/AutoPkg/Cache/com.github.jessepeterson.munki.ImageJ/downloads/ij.jar to /Users/*username*/Library/AutoPkg/Cache/com.github.jessepeterson.munki.ImageJ/pkgroot/Applications/ImageJ/ImageJ64.app/Contents/Resources/Java/ij.jar: [Errno 2] No such file or directory: u'/Users/*username*/Library/AutoPkg/Cache/com.github.jessepeterson.munki.ImageJ/pkgroot/Applications/ImageJ/ImageJ64.app/Contents/Resources/Java/ij.jar'`

Unarchiver seems to be working ok:

`Unarchiver
{'Input': {'archive_path': u'/Users/*username*/Library/AutoPkg/Cache/com.github.jessepeterson.munki.ImageJ/downloads/ImageJ.zip',
           'destination_path': u'/Users/*username*/Library/AutoPkg/Cache/com.github.jessepeterson.munki.ImageJ/pkgroot/Applications',
           'purge_destination': True}}
Unarchiver: Guessed archive format 'zip' from filename ImageJ.zip
Unarchiver: Unarchived /Users/*username*/Library/AutoPkg/Cache/com.github.jessepeterson.munki.ImageJ/downloads/ImageJ.zip to /Users/*username*/Library/AutoPkg/Cache/com.github.jessepeterson.munki.ImageJ/pkgroot/Applications`

Version of ImageJ downloaded and unarchived by recipe doesn't include ImageJ64.app. 

$ ls -l /Users/*username*/Library/AutoPkg/Cache/com.github.jessepeterson.munki.ImageJ/pkgroot/Applications/ImageJ

*ImageJ.app
*ImageJ32.app
*luts
*macros
*plugins

Issue with app version on NIH webserver, as implemented in #8 ?

**Comment by jessepeterson** [comment]
Looks like the download changed between ImageJ 1.48 and 1.49. In 1.48 the 32-bit version was the "default" and now the 64-bit version is default (i.e. named ImageJ.app). Easy enough change in the recipe but be sure to update your user's Dock and whatnot. :)
