### ISSUE TITLE
CUDADriver not MunkiImport'ing

### ISSUE THREAD

**Issue by jessepeterson** [autopkg/jessepeterson-recipes#17]
CUDADriver is not MunkiImporting for me in autopkg. MunkiImporter Processor claims it's already in the repo (as an older version). I believe this is due to the fact that because there is no installs key [MunkiImporter falls through](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/MunkiImporter.py#L263) to comparing the versions of the receipts key items and for CUDADriver apparently they don't change (they seem to all be "1.0" or "1" back through the oldest versions I have).

Before the CUDADriver recipe used to unpack the package and generate a Munki `installs` key. But that was changed in #1 (and again adjusted in 96167dd417b12fd2c9a28105b551df831150eb74).

We can go back to generating an `installs` key but this means unpacking the DMG and PKG again (I think part of the reason why #1 was proposed in the first place). This would allow MunkiImporter to compare something valid as the receipt versions in the `.pkg` don't seem to be maintained at all.

Thoughts? Paging @timsutton and @mkuron re: #1.

**Comment by mkuron** [comment]
I'll check my setup tomorrow, but from the code it looks like you're right.
We don't actually need to go back to unpacking, we can just add an installs section to the pkginfo that specifies _/Library/Frameworks/CUDA.framework_'s version as `%version%`. We already got that version number from the Nvidia web server.

**Comment by jessepeterson** [comment]
Ah, of course! We can just provide an additional key to the MunkiPkginfoMerger that's already there. I'll test that now.

**Comment by jessepeterson** [comment]
One note, this seemed to work before. I have at least one package in my repo without an `installs` key that autopkg put in there. I wonder if autopkg/autopkg@d201cb446acaedff1304ebe3f23b578cb269134f changed this. Either way an installs key is less ambiguous.

**Comment by jessepeterson** [comment]
So we now generate an `installs` key, but unfortunately MunkiImporter doesn't bother to do a version check on `bundle` type installs items. I'll submit a PR to autopkg.

**Comment by jessepeterson** [comment]
That was quick. :) Looks like @timsutton merged the change to autopkg.
