### ISSUE TITLE
VirtualBox recipe pulls 4.3.30 when 5.0.2 is available

### ISSUE THREAD

**Issue by poundbangbash** [autopkg/jessepeterson-recipes#18]
I just cloned and used your VirtualBox.munki recipe and was surprised when it pulled in version 4.3.30. when 5.0.2 is marked as the latest on virtualbox.org.  It appears Oracle is either faking us into using non-stable releases or haven't updated their update check url mechanism.

Using the URLs you use in the URLProvider I found they differ in version output:
ROOT_URL/LATEST_URL
    http://download.virtualbox.org/virtualbox/LATEST.TXT = 5.0.2
UPDATE_CHECK_URL
    https://update.virtualbox.org/query.php?platform=DARWIN_64BITS_GENERIC&version=4.3.16_95972&count=97&branch=stable = 4.3.30

**Comment by jessepeterson** [comment]
I have version 4.3.30 installed and when I go to the VirtualBox menu->Check for Updates... it says my version is 'up to date'. As you noticed the update check URL is returning the 4.3.x version.

The autopkg "wisdom" thus far is to interpret this as a reason why Oracle has no pushed out the newer version to existing users. I.e. something is unstable or not ready for production (and only users newly downloading it should get the new version).

Thus by those guidelines we should keep using the existing version. You're welcome to reach out to the Oracle folks and ask why their auto-updater has not offered the newer version. Perhaps it's just a mistake.

Cheers!

**Comment by jessepeterson** [comment]
@pudquick pointed this out on the autopkg wiki: https://github.com/autopkg/autopkg/wiki/FAQ#everyone-says-a-new-version-of-application-x-was-released-but-autopkg-doesnt-pick-it-up-why

**Comment by poundbangbash** [comment]
Interesting model they have there.   You'd think they'd want the latest software to be available to all, not just new installs.  Especially if it's not a solid release.  Nothing like bad first impressions.

I'm good with using version 4.3.30 if that's what they say is equally as current as their current web offering.  I just posted this issue to make sure they hadn't changed something on their update notification methods.  Thanks for taking time to look into it and explaining.

-Eric

On Aug 20, 2015, at 05:40 PM, Jesse Peterson <notifications@github.com> wrote:

I have version 4.3.30 installed and when I go to the VirtualBox menu->Check for Updates... it says my version is 'up to date'. As you noticed the update check URL is returning the 4.3.x version.
The autopkg "wisdom" thus far is to interpret this as a reason why Oracle has no pushed out the newer version to existing users. I.e. something is unstable or not ready for production (and only users newly downloading it should get the new version).
Thus by those guidelines we should keep using the existing version. You're welcome to reach out to the Oracle folks and ask why their auto-updater has not offered the newer version. Perhaps it's just a mistake.
Cheers!

**Comment by jessepeterson** [comment]
I'm going to close this ticket for now. It is *possible* they've forgotten to update the auto-update feed, though unlikely. If you want to reach out to the Oracle folks to ask them go for it. They have an IRC channel, mailing lists, and a ticketing system. Thanks!

**Comment by jessepeterson** [comment]
I'm re-opening this issue. I submitted a bug to the VirtualBox folks [here](https://www.virtualbox.org/ticket/14730). Hopefully they'll reply on what's up. In the meantime I'll try and track down the 5.x update feed.

**Comment by jessepeterson** [comment]
They marked that [issue](https://www.virtualbox.org/ticket/14730) as 'fixed' but said:

> Fixed. For 'stable', the current version is now 4.3.32. For 'all / with betas', the current version is 5.0.8. The 'stable' channel will switch to 5.0.x soon.

So it appears 5.0.x is not considered stable by Oracle/VirtualBox folks, FWIW.

**Comment by poundbangbash** [comment]
Thanks for following up.  As long as the recipe is working I'm good with what's coming out of it.
Interesting that their main direct download is a "beta" and getting to the "stable" release isn't obvious from the landing page and buried under version 5 info on the Downloads page.  ¯\_(ツ)_/¯
