### ISSUE TITLE
VMwareTools recipe needs to be updated now that Fusion 8 is now out

### ISSUE THREAD

**Issue by rtrouton** [autopkg/jessepeterson-recipes#19]
Please change the **DEFAULT_VERSION_SERIES** value stored in VMwareToolsURLProvider.py from 7 to 8, now that VMware Fusion 8.0.0 has been released:

https://github.com/autopkg/jessepeterson-recipes/blob/master/VMware/VMwareToolsURLProvider.py#L13

**Comment by jessepeterson** [comment]
Thanks for the head-up, Rich. After changing that are you getting any newer version than 9.9.3? I seem to already have that version retrieved from autopkg.

**Comment by rtrouton** [comment]
Yes, I'm now getting VMware Tools 10.0.0. When I inspected it with Pacifist, it looks like the same version of Tools that is included with VMware Fusion 8.0.0.

![screen shot 2015-08-25 at 1 51 29 pm](https://cloud.githubusercontent.com/assets/618055/9474752/84b7354a-4b30-11e5-8da2-00c770e072bf.png)
![screen shot 2015-08-25 at 12 50 13 pm](https://cloud.githubusercontent.com/assets/618055/9474753/84bc1e66-4b30-11e5-8623-cab28d09747e.png)

**Comment by jessepeterson** [comment]
Odd, I'm only getting 9.9.3 with the latest change.

**Comment by rtrouton** [comment]
I removed the relevant folder from ~/Library/AutoPkg/Cache, to force it to download a new copy of everything. At that point, I got 10.0.0.

**Comment by jessepeterson** [comment]
Ah, indeed, thanks! Looks like the file sizes match on the download and autopkg assumes they're the same. Have to figure out a solution to that one.

**Comment by jessepeterson** [comment]
So it looks like indeed the filesizes are the same for each download ([1](http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/7.1.2/2779224/packages/com.vmware.fusion.tools.darwin.zip.tar) and [2](http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/8.0.0/2985594/packages/com.vmware.fusion.tools.darwin.zip.tar)) but they *do* have differing `Last-Modified` headers. However autopkg doesn't check the headers: it only submits a `If-Modified-Since` header and I'd guess the HTTP server at softwareupdate.vmware.com doesn't support it.

This raises the question of whether we should lobby autopkg to support some logic to check Last-Modified dates in the URLDownloader processor.

**Comment by timsutton** [comment]
Just a quick observation: I get a 304 if I provide both If-Modified-Since and If-None-Match, and if I provide only If-Modified-Since. If I provide only If-None-Match, I get a 200 and the content. URLDownloader _should_ be providing both headers assuming it stored them both with the downloaded file.

```
curl \
> -v \
> -H 'If-Modified-Since: Fri, 14 Aug 2015 22:30:00 GMT' \
> -H 'If-None-Match: "b7ae0023c1a193f75fd3a03f56ffbd9f:1440480904"' \
> http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/8.0.0/2985594/packages/com.vmware.fusion.tools.darwin.zip.tar
*   Trying 23.203.64.44...
* Connected to softwareupdate.vmware.com (23.203.64.44) port 80 (#0)
> GET /cds/vmw-desktop/fusion/8.0.0/2985594/packages/com.vmware.fusion.tools.darwin.zip.tar HTTP/1.1
> Host: softwareupdate.vmware.com
> User-Agent: curl/7.43.0
> Accept: */*
> If-Modified-Since: Fri, 14 Aug 2015 22:30:00 GMT
> If-None-Match: "b7ae0023c1a193f75fd3a03f56ffbd9f:1440480904"
>
< HTTP/1.1 304 Not Modified
< Content-Type: application/x-tar
< Last-Modified: Fri, 14 Aug 2015 22:30:00 GMT
< ETag: "b7ae0023c1a193f75fd3a03f56ffbd9f:1440480904"
< Date: Tue, 25 Aug 2015 20:57:15 GMT
< Connection: keep-alive
<
* Connection #0 to host softwareupdate.vmware.com left intact
```

**Comment by jessepeterson** [comment]
Hmm. I see that the 7.1.2 file currently provides both an `ETag` and a `Last-Modified` header.  Of course my original download is now gone so I can't see what extended attributes were set on it.

**Comment by jessepeterson** [comment]
@timsutton: When I provide both an ETag and Last-Modified header of the *older* file get a 200, not a 304 from the server:

```
% curl -o /dev/null -v -H 'If-None-Match: 7c38e2a9ae73fa879b8035def8dbed91:1434599156' -H 'If-Modified-Since: Sun, 31 May 2015 03:37:12 GMT' http://softwareupdate.vmware.com/cds/vmw-desktop/fusion/8.0.0/2985594/packages/com.vmware.fusion.tools.darwin.zip.tar
* Adding handle: conn: 0x7f881480c000
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7f881480c000) send_pipe: 1, recv_pipe: 0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0* About to connect() to softwareupdate.vmware.com port 80 (#0)
*   Trying 23.208.227.51...
* Connected to softwareupdate.vmware.com (23.208.227.51) port 80 (#0)
> GET /cds/vmw-desktop/fusion/8.0.0/2985594/packages/com.vmware.fusion.tools.darwin.zip.tar HTTP/1.1
> User-Agent: curl/7.30.0
> Host: softwareupdate.vmware.com
> Accept: */*
> If-None-Match: 7c38e2a9ae73fa879b8035def8dbed91:1434599156
> If-Modified-Since: Sun, 31 May 2015 03:37:12 GMT
> 
< HTTP/1.1 200 OK
* Server Apache is not blacklisted
< Server: Apache
< ETag: "b7ae0023c1a193f75fd3a03f56ffbd9f:1440480904"
< Last-Modified: Fri, 14 Aug 2015 22:30:00 GMT
< Accept-Ranges: bytes
< Content-Length: 2560000
< Content-Type: application/x-tar
< Date: Wed, 26 Aug 2015 03:13:55 GMT
< Connection: keep-alive
< 
{ [data not shown]
100 2500k  100 2500k    0     0  3186k      0 --:--:-- --:--:-- --:--:-- 3196k
* Connection #0 to host softwareupdate.vmware.com left intact
```

I now think this is *correct* web server behavior: it's just that the file sizes match and URLDownloader thinks they're the same file, no? Perhaps we simply need to check that an ETag doesn't exist before we assume a file size match makes the decision.

**Comment by jessepeterson** [comment]
autopkg/autopkg#219 has a fix commited (thanks @timsutton)
