### ISSUE TITLE
Separate out the parts

### ISSUE THREAD

**Issue by seansgm** [autopkg/jessepeterson-recipes#22]
Before I look to duplicate this, I don't suppose you want to separate the parts: download, pkg, munki, into individual recipes with child/parent relationship, for use beyond Munki?

**Comment by jessepeterson** [comment]
This has been on my list for a while. Happily accepting PRs. :)

**Comment by jessepeterson** [comment]
I'm gonna close this ticket. It's a noble goal but time is limiting me to accepting PRs at this point. Thanks!

**Comment by seansgm** [comment]
You've already accepted the recipe I supplied split into parts.

https://github.com/autopkg/jessepeterson-recipes/pull/24
