### ISSUE TITLE
DmgCreator bug strikes again

### ISSUE THREAD

**Issue by paulsuh** [autopkg/jessepeterson-recipes#26]
> The following recipes failed:
>     PDFpenPro.munki.recipe
>         Error in com.github.jessepeterson.PDFpenPro.munki: Processor: DmgCreator: Error: creation of /Users/Shared/Jenkins/Library/AutoPkg/Cache/com.github.jessepeterson.PDFpenPro.munki/PDFpenPro.dmg failed: hdiutil: create failed - error -5341

Actual size is 123 MB, so adding a dmg_megabytes -> 128 seems to fix it. That leaves about 5 MB free on the dmg.

**Comment by gregneagle** [comment]
Of course this is not a bug in DmgCreator; it's a bug in `hdiutil create`. DmgCreator has a feature you can use to work around the `hdutil` bug.

**Comment by jessepeterson** [comment]
@paulsuh I've been successfully packaging up PDFPen & PDFPen pro packages for a bit now. What OS are you running autopkg on?
