### ISSUE TITLE
Dockutil package install a non-executable command

### ISSUE THREAD

**Issue by ygini** [autopkg/jessepeterson-recipes#27]
The dockutil command installed via the package miss the executable flag.

chmod +x /usr/local/bin/dockutil is needed as postinstall script in the package.

**Comment by jessepeterson** [comment]
Is with the `dockutil.pkg.munki`? The munki recipe properly sets the permissions [here](https://github.com/autopkg/jessepeterson-recipes/blob/master/dockutil/dockutil.munki.recipe#L110). If you'd like to submit a PR for the pkg recipe I will gladly merge! I don't use the pkg recipe. Thanks!

**Comment by gregneagle** [comment]
Better to fix the payload in the pkg than add a postinstall script!

**Comment by ygini** [comment]
Indeed, it would be better to fix the pkg instead of postinstall script specific to munki. 

If you do it in the pkg it will be done for every kind of usage (Munki and others).

**Comment by jessepeterson** [comment]
Actually the Munki recipe doesn't depend on the .pkg recipe (nor the download recipe, it seems). I prefer to not mess with .pkg installers when not strictly necessary. So: sure, I'm happily accepting PRs to fix the pkg payload. :) This would be adding `mode` to the `pkg_request` I'd guess?
