### ISSUE TITLE
Dockutil download recipe keeps re-downloading

### ISSUE THREAD

**Issue by aysiu** [autopkg/jessepeterson-recipes#40]
I think you figured out on Slack that it was because there were changes made to the binary. Perhaps instead of having the download link be https://raw.github.com/kcrawford/dockutil/master/scripts/dockutil just go with the latest link on the releases page?
https://github.com/kcrawford/dockutil/releases

**Comment by jessepeterson** [comment]
This was fixed by using dockutil's releases page instead as suggested by @aysiu (see #41 and 09a528e3aabe2c236432b259ca0d3a2524a53eac).
