### ISSUE TITLE
VirtualBoxExtPack.munki postinstall hangs due to ToC prompt

### ISSUE THREAD

**Issue by klou** [autopkg/jessepeterson-recipes#47]
With the 5.1.20 run, VirtualBoxExtPack.munki.recipe postinstall script seems to hang upon installation.
```
$VBM extpack install --replace \
	/tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack
```
When the above is run manually, it prints a Terms and Conditions agreement prompt (which explains the hang upon installation).  Any suggestions for bypassing?

**Comment by jessepeterson** [comment]
Hi @klou can you test the modification? Thanks!

**Comment by klou** [comment]
Duh, that's a simple fix!  It works for me, thanks!

I'm guessing that the following "batch installation" string is a per-site generated license key.

**Comment by jessepeterson** [comment]
@klou: "batch installation" string?

**Comment by llauren** [comment]
The installer suggests adding `--accept-license=715c7246dc0f779ceab39446812362b2f9bf64a55ed5d3a905f053cfab36da9e` to the installation script, but if that string ever changes, i think the `echo y|` hack is way niftier :)

**Comment by jessepeterson** [comment]
Looks like homebrew is doing that method. I'd probably prefer to do it the more supported way.

https://github.com/caskroom/homebrew-cask/blob/master/Casks/virtualbox-extension-pack.rb

**Comment by klou** [comment]
Looks like that license string persists for 5.1.22, so you'll probably be good in using it.

**Comment by jessepeterson** [comment]
Is it a per-version license string? I'd hate to be caught in a per-version update cycle perversion.

**Comment by RicknTx** [comment]
I've updated my repo and validated that it has the new recipe with the echo y in there, but it still seems to stall at Running postinstall_script for VirtualBoxExtPack.  If I run the command manually, I can see it answering y and then moving on.  Is there something else possibly in my recipe that is broken that I should look for?  On a ps I see it is stuck at '/Applications/VirtualBox.app/Contents/MacOS/VBoxManage extpack install --replace /tmp/Oracle_VM_VirtualBox_Extension_Pack.vbox-extpack' and it isn't running the variable specified one at '/usr/local/bin/VBoxManage'

**Comment by MichalMMac** [comment]
Current workaround with `echo y|` seems to work ok. Thanks! :-)

**Comment by KSchmeeds** [comment]
I'm seeing this issue on my deployment with Munki and the VirutualBox extension package.

 Do you agree to these license terms and conditions (y/n)?
    License accepted. For batch installaltion add
    --accept-license=56be48f923303c8cababb0bb4c478284b688ed23f16d775d729b89a2e8e5f9eb
    to the VBoxManage command line.

I'm not sure where in the script to add this, otherwise I would create a PR.

**Comment by jessepeterson** [comment]
Did the current fix for this break again?

**Comment by KSchmeeds** [comment]
Unfortunately it appears so.  It looks like the extension pack gets stuck in a munki installation loop because it fails to update.

**Comment by KSchmeeds** [comment]
I just created pull request #62 to resolve this issue.  I think the main issue is with using echo y | munki sees the output as an error, as every time this install runs on a client, munkireport shows 146 errors and the error context is the EULA.

**Comment by jessepeterson** [comment]
Was this a new new update to VirtualBox? This fix has been working fine for 8 months or so.

**Comment by jessepeterson** [comment]
#62 merged. I think we can consider this closed.
