### ISSUE TITLE
UTC 6.1.4 code signature broken

### ISSUE THREAD

**Issue by rickheil** [autopkg/jessepeterson-recipes#50]
$ codesign --verify --verbose=1 /Applications/Universal\ Type\ Client.app/
/Applications/Universal Type Client.app/: nested code is modified or invalid
file modified: /Applications/Universal Type Client.app/Contents/Frameworks/cpp-core.framework
file modified: /Applications/Universal Type Client.app/Contents/Frameworks/Sparkle.framework
file modified: /Applications/Universal Type Client.app/Contents/Frameworks/HDCrashReporter.framework
file modified: /Applications/Universal Type Client.app/Contents/Frameworks/ExtensisFontManagement.framework

I've opened up a support ticket with them. In the mean time, the recipe breaks if you don't pass -k DISABLE_CODE_SIGNATURE_VERIFICATION=1

**Comment by jessepeterson** [comment]
This is a constant problem with Extensis breaking their own code signature. See e.g. #23, too.

**Comment by rickheil** [comment]
Not entirely surprising... A few of us were talking about it on Slack so I wanted to put an issue here so people were aware the problem isn't with the recipe, but rather with the vendor. I'll update when I get a reply from them but I'm not totally hopeful.

**Comment by jessepeterson** [comment]
Usually their response is simply "yeah, we know, deal with it until the next released version".

**Comment by rickheil** [comment]
Their reply this time was "oh, we fixed it!"

It wasn't fixed.

Sent from my iPhone

On Aug 4, 2017, at 17:23, Jesse Peterson <notifications@github.com<mailto:notifications@github.com>> wrote:


Usually their response is simply "yeah, we know, deal with it until the next released version".

**Comment by jessepeterson** [comment]
Looks like 6.1.5 is fixed now. Closing this (until Extensis breaks it again).
