### ISSUE TITLE
VMwareTools doesn't pull the latest version

### ISSUE THREAD

**Issue by flammable** [autopkg/jessepeterson-recipes#53]
Hey Jesse!

I'm not sure why, but the VMware Tools recipe isn't downloading the latest version.  I'm probably doing something wrong, but I tried setting `DEFAULT_VERSION_SERIES` to `10.0.0`, but had no luck.  Now that I'm writing this, I've realized it's probably not something I can specify in the recipe override.

The latest version of the tools can be found here:

https://softwareupdate.vmware.com/cds/vmw-desktop/fusion/10.0.1/6754183/packages/com.vmware.fusion.tools.darwin.zip.tar

I ran my override like this, and it imported the new pkg OK:

`autopkg run -v local.munki.VMwareTools -p /path/to/com.vmware.fusion.tools.darwin.zip.tar `

Mike

**Comment by jessepeterson** [comment]
Merged in #55 and #59. Thanks!
